apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netsentinel-attu-route
  namespace: milvus-operator
  labels:
    app: attu
spec:
  to:
    kind: Service
    name: netsentinel-attu-svc
  port:
    targetPort: attu
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: netsentinel-attu-svc
  namespace: milvus-operator
  labels:
    app: attu
spec:
  type: ClusterIP
  ports:
    - name: attu
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: attu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsentinel-attu
  namespace: milvus-operator
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
        - name: attu
          image: zilliz/attu:v2.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: attu
              containerPort: 3000
              protocol: TCP
          env:
            - name: MILVUS_URL
              value: "netsentinel-milvus:19530"
