apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: netsentinel-triton
  namespace: netsentinel
  labels:
    name: netsentinel-triton
    opendatahub.io/dashboard: "true"
  annotations:
    enable-route: "true"
    maxLoadingConcurrency: "1"
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: Triton runtime 24.11-py3
    opendatahub.io/template-name: triton-24.11-py3-template
    openshift.io/display-name: netsentinel-triton
spec:
  supportedModelFormats:
    - name: keras
      version: "2"
      autoSelect: true
    - name: onnx
      version: "1"
      autoSelect: true
    - name: pytorch
      version: "1"
      autoSelect: true
    - name: tensorflow
      version: "1"
      autoSelect: true
    - name: tensorflow
      version: "2"
      autoSelect: true
    - name: tensorrt
      version: "7"
      autoSelect: true
  protocolVersions:
    - grpc-v2
  multiModel: true
  grpcEndpoint: port:8085
  grpcDataEndpoint: port:8001
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  containers:
    - name: triton
      image: nvcr.io/nvidia/tritonserver:24.11-py3
      command:
        - /bin/sh
      args:
        - -c
        - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models;
          exec tritonserver "--model-repository=/models/_triton_models"
          "--model-control-mode=explicit" "--strict-model-config=false"
          "--strict-readiness=false" "--allow-http=true"
          "--allow-sagemaker=false" '
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      resources:
        requests:
          cpu: "4"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 16Gi
      livenessProbe:
        exec:
          command:
            - curl
            - --fail
            - --silent
            - --show-error
            - --max-time
            - "9"
            - http://localhost:8000/v2/health/live
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 10
  builtInAdapter:
    serverType: triton
    runtimeManagementPort: 8001
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
