apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - console-operators.operatorgroup.yaml
  - console-prometheus-server.clusterrole.yaml
  - console-prometheus-server.clusterrolebinding.yaml
  - console-prometheus-server.serviceaccount.yaml
  - console-prometheus.prometheus.yaml
  - kafka-resources.podmonitor.yaml
  - kubernetes-scrape-configs.secret.yaml