apiVersion: v1
kind: ConfigMap
metadata:
  name: netsentinel-zeek-config
data:
  node.cfg: |
    [zeek]
    type=standalone
    host=localhost
    interface=br-ex

  zeekctl.cfg: |
    # ZeekControl configuration
    MailTo = root@localhost
    LogDir = /usr/local/zeek/logs
    SpoolDir = /usr/local/zeek/spool
    PidFile = /usr/local/zeek/spool/zeekctl.pid
    ScriptsDir = /usr/local/zeek/scripts

  local.zeek: |
    @load base/frameworks/cluster
    @load base/frameworks/logging

    # Load required packages
    @load packages/zeek-kafka

    redef ignore_checksums = T;

    # Disable global topic name to allow per-log topic configuration
    redef Kafka::topic_name = "";
    redef Kafka::kafka_conf = table(
        ["debug"] = "all",
        ["metadata.broker.list"] = "console-kafka-kafka-secure-bootstrap:9093",
        ["security.protocol"] = "SASL_SSL",
        ["sasl.mechanisms"] = "SCRAM-SHA-512",
        ["sasl.username"] = "netsentinel-zeek-client",
        ["sasl.password"] = getenv("KAFKA_PASSWORD"),
        ["ssl.ca.location"] = "/usr/local/share/ca-certificates/ca.crt",
    );
    redef Kafka::tag_json = T;

    event zeek_init() &priority=-10
    {
        # Define log filters directly for each log type

        local http_filter: Log::Filter = [
            $name = "kafka-http",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-http"),
            $path = "netsentinel-kafka-zeek-http"
        ];
        Log::add_filter(HTTP::LOG, http_filter);

        local dns_filter: Log::Filter = [
            $name = "kafka-dns",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-dns"),
            $path = "netsentinel-kafka-zeek-dns"
        ];
        Log::add_filter(DNS::LOG, dns_filter);

        local conn_filter: Log::Filter = [
            $name = "kafka-conn",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-conn"),
            $path = "netsentinel-kafka-zeek-conn"
        ];
        Log::add_filter(Conn::LOG, conn_filter);

        local dpd_filter: Log::Filter = [
            $name = "kafka-dpd",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-dpd"),
            $path = "netsentinel-kafka-zeek-dpd"
        ];
        Log::add_filter(DPD::LOG, dpd_filter);

        local ftp_filter: Log::Filter = [
            $name = "kafka-ftp",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-ftp"),
            $path = "netsentinel-kafka-zeek-ftp"
        ];
        Log::add_filter(FTP::LOG, ftp_filter);

        local files_filter: Log::Filter = [
            $name = "kafka-files",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-files"),
            $path = "netsentinel-kafka-zeek-files"
        ];
        Log::add_filter(Files::LOG, files_filter);

        local smtp_filter: Log::Filter = [
            $name = "kafka-smtp",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-smtp"),
            $path = "netsentinel-kafka-zeek-smtp"
        ];
        Log::add_filter(SMTP::LOG, smtp_filter);

        local ssl_filter: Log::Filter = [
            $name = "kafka-ssl",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-ssl"),
            $path = "netsentinel-kafka-zeek-ssl"
        ];
        Log::add_filter(SSL::LOG, ssl_filter);

        local weird_filter: Log::Filter = [
            $name = "kafka-weird",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-weird"),
            $path = "netsentinel-kafka-zeek-weird"
        ];
        Log::add_filter(Weird::LOG, weird_filter);

        local notice_filter: Log::Filter = [
            $name = "kafka-notice",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-notice"),
            $path = "netsentinel-kafka-zeek-notice"
        ];
        Log::add_filter(Notice::LOG, notice_filter);

        local dhcp_filter: Log::Filter = [
            $name = "kafka-dhcp",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-dhcp"),
            $path = "netsentinel-kafka-zeek-dhcp"
        ];
        Log::add_filter(DHCP::LOG, dhcp_filter);

        local ssh_filter: Log::Filter = [
            $name = "kafka-ssh",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-ssh"),
            $path = "netsentinel-kafka-zeek-ssh"
        ];
        Log::add_filter(SSH::LOG, ssh_filter);

        local software_filter: Log::Filter = [
            $name = "kafka-software",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-software"),
            $path = "netsentinel-kafka-zeek-software"
        ];
        Log::add_filter(Software::LOG, software_filter);

        local radius_filter: Log::Filter = [
            $name = "kafka-radius",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-radius"),
            $path = "netsentinel-kafka-zeek-radius"
        ];
        Log::add_filter(RADIUS::LOG, radius_filter);

        local x509_filter: Log::Filter = [
            $name = "kafka-x509",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-x509"),
            $path = "netsentinel-kafka-zeek-x509"
        ];
        Log::add_filter(X509::LOG, x509_filter);

        local rfb_filter: Log::Filter = [
            $name = "kafka-rfb",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-rfb"),
            $path = "netsentinel-kafka-zeek-rfb"
        ];
        Log::add_filter(RFB::LOG, rfb_filter);

        local sip_filter: Log::Filter = [
            $name = "kafka-sip",
            $writer = Log::WRITER_KAFKAWRITER,
            $config = table(["topic_name"] = "netsentinel-kafka-zeek-sip"),
            $path = "netsentinel-kafka-zeek-sip"
        ];
        Log::add_filter(SIP::LOG, sip_filter);
    }

    redef Telemetry::metrics_port = 9999/tcp;
