apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeek-privileged
  namespace: netsentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeek-privileged-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeek-privileged-binding
subjects:
- kind: ServiceAccount
  name: zeek-privileged
  namespace: netsentinel
roleRef:
  kind: ClusterRole
  name: zeek-privileged-role
  apiGroup: rbac.authorization.k8s.io
