apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - console-server.clusterrole.yaml
  - console-server.clusterrolebinding.yaml
  - console-server.serviceaccount.yaml
  - console-ui.route.yaml
  - console-ui.service.yaml
  - console.deployment.yaml
