# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: netsentinel
---
# Secret with OpenAI API key
apiVersion: v1
kind: Secret
metadata:
  name: kubectl-ai-secret
  namespace: netsentinel
type: Opaque
stringData:
  OPENAI_API_KEY: "<insert-your-secret-key-here>"
---
# ConfigMap with AI config
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubectl-ai-config
  namespace: netsentinel
data:
  OPENAI_API_BASE: "https://granite-3-8b-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1"
  LLM_PROVIDER: "openai"
  LLM_MODEL: "granite-3-8b-instruct"
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-ai-api
  namespace: netsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-ai-api
  template:
    metadata:
      labels:
        app: kubectl-ai-api
    spec:
      serviceAccountName: kubectl-ai-sa
      containers:
        - name: kubectl-ai-api
          image: quay.io/bpandey/netsentinel-kubectl-ai:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: kubectl-ai-config
            - secretRef:
                name: kubectl-ai-secret
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: kubectl-ai-api
  namespace: netsentinel
spec:
  selector:
    app: kubectl-ai-api
  ports:
    - name: http
      port: 80
      targetPort: 8088
---
# Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kubectl-ai-api
  namespace: netsentinel
spec:
  to:
    kind: Service
    name: kubectl-ai-api
  port:
    targetPort: http
  tls:
    termination: edge
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-ai-sa
  namespace: netsentinel
---
# Role (namespace-scoped permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-ai-role
  namespace: netsentinel
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-ai-rolebinding
  namespace: netsentinel
subjects:
  - kind: ServiceAccount
    name: kubectl-ai-sa
    namespace: netsentinel
roleRef:
  kind: Role
  name: kubectl-ai-role
  apiGroup: rbac.authorization.k8s.io
