kind: SecurityContextConstraints
metadata:
  name: milvus-operator-privileged-scc
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - "*"
supplementalGroups:
  type: RunAsAny
users:
  - system:admin
  - system:serviceaccount:milvus-operator:milvus-operator
  - system:serviceaccount:milvus-operator:milvus-operator-checker
  - system:serviceaccount:milvus-operator:netsentinel-minio
  - system:serviceaccount:milvus-operator:default
volumes:
  - "*"
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - "*"
allowedUnsafeSysctls:
  - "*"
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:cluster-admins
  - system:nodes
  - system:masters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-operator-scc-access
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
      - get
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: milvus-operator-scc-binding
subjects:
  - kind: ServiceAccount
    name: milvus-operator
    namespace: milvus-operator
roleRef:
  kind: ClusterRole
  name: milvus-operator-scc-access
  apiGroup: rbac.authorization.k8s.io
