apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitoring-view-binding
subjects:
- kind: ServiceAccount
  name: telcolab-netsentinel-sa
  namespace: netsentinel
