apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocpclient-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: telcolab-netsentinel-sa
    namespace: netsentinel
roleRef:
  kind: ClusterRole
  name: ocpclient-clusterrole
  apiGroup: rbac.authorization.k8s.io
