apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: console-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      type: simple
    config:
      allow.everyone.if.no.acl.found: 'true'
      default.replication.factor: 3
      inter.broker.protocol.version: '3.7'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: secure
        port: 9093
        tls: true
        type: route
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            host: console-kafka-kafka-secure-bootstrap
            annotations:
              eyefloaters.github.com/console-listener: 'true'
          brokers:
          - broker: 0
            host: console-kafka-kafka-secure-0
          - broker: 1
            host: console-kafka-kafka-secure-1
          - broker: 2
            host: console-kafka-kafka-secure-2
    replicas: 3
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: console-kafka-metrics
          key: kafka-metrics-config.yml
    version: 3.7.0
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: console-kafka-metrics
          key: zookeeper-metrics-config.yml
