apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ../../../base

patches:
  - target:
      kind: Deployment
      name: ngrok
    path: deployment-ngrok-delete.patch.yaml
  - target:
      kind: Secret
      name: ngrok-token
    path: secret-ngrok-token-delete.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: ocpclient-clusterrolebinding
    path: clusterrolebinding.patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: cluster-monitoring-view-binding
    path: cluster-monitoring-view-binding.patch.yaml

configMapGenerator:
  - name: app-config
    files:
      - config.yaml=app-config.yaml
    behavior: replace
