apiVersion: v1
kind: Secret
metadata:
  name: app-config-secret
type: Opaque
stringData:
  secret.yaml: |
    models:
      llm:
        token: "your-real-llm-token"
    slack:
      bot_token: "your-slack-token"
      signing_secret: "your-slack-signing-secret"
