{{- if .Values.createAppSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: app-config-secret
  annotations:
    "argocd.argoproj.io/sync-options": "Skip"
type: Opaque
stringData:
  secret.yaml: |
    models:
      llm:
        token: "{{ .Values.secrets.llm.token }}"
    slack:
      bot_token: "{{ .Values.secrets.slack.bot_token }}"
      signing_secret: "{{ .Values.secrets.slack.signing_secret }}"
{{- end }}
