apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocpclient-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "events"]
    verbs: ["get", "list", "watch", "create", "exec"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitoring-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: netsentenial-sa
    namespace: netsentenial
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocpclient-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: netsentenial-sa
    namespace: netsentenial
roleRef:
  kind: ClusterRole
  name: ocpclient-clusterrole
  apiGroup: rbac.authorization.k8s.io
