apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netsentinel-route
  labels:
    app.kubernetes.io/name: netsentinel
    app.kubernetes.io/instance: netsentinel-001
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: netsentinel-system
    app.kubernetes.io/managed-by: OpenShift
spec:
  to:
    kind: Service
    name: netsentinel-service
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None