apiVersion: v1
kind: Service
metadata:
  name: netsentinel-service
  labels:
    app.kubernetes.io/name: netsentinel
    app.kubernetes.io/instance: netsentinel-001
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: netsentinel-system
    app.kubernetes.io/managed-by: OpenShift
spec:
  selector:
    app.kubernetes.io/name: netsentinel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
