apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsentinel

resources:
  - ../../../base/kafka
  - console-ui-secrets.yaml

patchesStrategicMerge:
  - patches/console-ui.route.yaml
  - patches/console-server.clusterrolebinding.yaml
  - patches/console.deployment.yaml
  - patches/console-kafka.kafka.yaml
  - patches/console-operators.operatorgroup.yaml
  - patches/console-prometheus-server.clusterrolebinding.yaml
